@manassa_ticket_backend_HostAddress = http://localhost:5119

GET {{manassa_ticket_backend_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{manassa_ticket_backend_HostAddress}}/ticket/id/00000000-0000-0000-0000-000000000000
Accept: application/json

###
